---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  # - name: ubuntu-14.04
  # - name: ubuntu-16.04
  - name: ubuntu-18.04
  # - name: centos-6
  - name: centos-7
  # - name: debian-7
  # - name: debian-8
  # - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[test::all-in-one]
    attributes:
