---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[cloudstack::management_server]
      - recipe[cloudstack::usage]
    attributes:
  - name: acs46
    run_list:
      - recipe[cloudstack::management_server]
      - recipe[cloudstack::usage]
    attributes: 
      cloudstack: 
        release_major: '4.6'
