defaults: &defaults
  docker:
    - image: chef/chefdk:3.6.57
  working_directory: ~/cookbook/cookbook_cloudstack

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
    - checkout
    - save_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - ~/cookbook/cookbook_cloudstack

  cookstyle:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run:
        name: "Chef and Ruby version"
        command: |
          chef --version
          ruby --version
    - run:
        name: "Check Cookstyle"
        command: chef exec cookstyle .

  foodcritic:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run:
        name: "Chef and Ruby version"
        command: |
          chef --version
          ruby --version
    - run:
        name: "Check Foodcritic"
        command: chef exec foodcritic .

  chefspec:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run:
        name: "Chef and Ruby version"
        command: |
          chef --version
          ruby --version
    - run:
        name: "Check Serverspec"
        command: chef exec rspec spec

  kitchen:
    machine: true
    services:
      - docker
    steps:
    - checkout
    - run:
        name: "Install Chef"
        command: |
          wget https://packages.chef.io/files/stable/chefdk/3.6.57/ubuntu/18.04/chefdk_3.6.57-1_amd64.deb
          sudo dpkg -i chefdk_3.6.57-1_amd64.deb
    - run:
        name: "Chef and Ruby version"
        command: |
          chef --version
          ruby --version
    - run:
        name: "Install Gem, Cookbooks dependencies"
        command: |
          chef exec bundle install
          berks install
          berks update
    - run:
        name: "Run Kitchen test"
        command: KITCHEN_LOCAL_YAML=.kitchen.docker.yml kitchen test --destroy always

workflows:
  version: 2
  build:
    jobs:
    - checkout:
        filters:
          tags:
            only: /v.*/

    - cookstyle:
        requires:
          - checkout
        filters:
          tags:
            only: /v.*/

    - foodcritic:
        requires:
          - checkout
        filters:
          tags:
            only: /v.*/

    - chefspec:
        requires:
          - checkout
        filters:
          tags:
            only: /v.*/

    - kitchen:
        requires:
          - checkout
        filters:
          tags:
            only: /v.*/
